# Generated by Django 2.2.2 on 2019-07-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='UserID')),
                ('nickname', models.CharField(blank=True, max_length=50, unique=True, verbose_name='昵称')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('IDCard', models.CharField(max_length=20, verbose_name='身份证号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子信箱')),
                ('province', models.CharField(max_length=10, verbose_name='省')),
                ('city', models.CharField(max_length=10, verbose_name='市')),
                ('county', models.CharField(max_length=10, verbose_name='县')),
                ('nation', models.CharField(max_length=10, verbose_name='民族')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='电话号')),
                ('registerTime', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
            ],
        ),
    ]
