# Generated by Django 2.2.2 on 2019-07-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1', max_length=20, verbose_name='密码'),
        ),
    ]
