# Generated by Django 2.2.2 on 2019-06-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
